name: Rady dependency solver

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited, ready_for_review]

permissions: {}

jobs:
  rady:
    permissions:
      contents: write
      pull-requests: write
    uses: keys-i/dependasolver/.github/workflows/solve.yml@408eeb3c9df835e234b3a6e4f2124b15f9322732
    with:
      app-client-id: ${{ vars.DEPENDASOLVER_APP_CLIENT_ID }}
      required-checks: '["test", "audit", "dependency-review"]'
    secrets:
      app-private-key: ${{ secrets.DEPENDASOLVER_APP_PRIVATE_KEY }}
